<?php

/**
*
* Diese Datei sollte enthalten
* Übersetzungsstring für Deutsch
*
*/
$sch_user_defined_de_languages_strings = [
	"branch_created" => "Zweig erstellt",
	"fuehrerscheinantrag" => "Führerscheinantrag", 
	"theorieunterricht" => "Theorieunterricht", 
	"praktischer_unterricht" => "Praktischer Unterricht", 
	"hinweise" => "Hinweise", 
	"hinweise_zur_ausbildung" => "Hinweise zur Ausbildung", 
	"hinweise_zur_prufueng" => "Hinweise zur Prufüng", 
	"tipps" => "Tipps", 
	"manage_notes" => "Hinweise Verwalten. Zum bearbeiten, klicken Sie auf einen Hinweis oder ein Wort. Wenn Sie einen Hinweis mit der Überschrift 'Hinweise' erstellen, wird die Überschrift in der App in Rot angezeigt.",
	"manage_view" => "Gestalten Sie, wie diese Seite in der App aussieht.",
	"hinweis_hinzufuegen" => "Gruppe erstellen", 
	"hinweise_bearbeiten_und_erstellen" => "Hinweise bearbeiten und erstellen", 
	"hinweisenname" => "Hinweisenname", 
	"hinweisenueberschrift" => "Hinweisenüberschrift",
	"hinweisentext" => "Hinweisentext", 
	"cancel" => "Abbrechen", 
	"hinweis_loeschen" => "Hinweis löschen",
	"hinweis_gespeichert" => "Hinweis gespeichert", 
	"hinweis_wurde_erfolgreich_geloescht" => "Hinweis wurde erfolgreich gelöscht", 
	"back" => "Zurück",
	
	"all_child_notes_will_be_deleted"=>"Vorsicht! Wenn Sie eine Hinweisgruppe löschen, werden alle Hinweise in dieser Gruppe auch gelöscht.",
	"fuehrerscheinantrag_description"=>"Hier können Sie die notwendigen Unterlagen als Hinweise für die Fahrschüler auslisten.",
	"add_new_line" => "Neue Zeile Hinzufügen",
	"auflistungsart" => "Auflistungsart", 
	"auflistungsart_desc" => "Wie sollen die Hinweise in der App dargestellt werden", 
	"checkbox" => "Mit einer Checkbox", 
	"akkordion" => "Mit einem Akkordion", 
	"checkbox_desc" => "Diese Liste wird als eine Checkbox in der App dargestellt.", 
	"akkordion_desc" => "Diese Liste wird als ein Akkordion in der App dargestellt.", 
	"to_group_adden" => "Hinweis zur Gruppe Hinzufügen", 
	"to_group_adden_with_var" => "Hinweis zu(r) __1__ Hinzufügen", 
	"empty_here_in"=>"Keine Einträge verfügbar in '__1__'",
	"vorschau_ansehen" => "Darstellung in der App Ansehen", 
	"hinweise_hinzufuegen" => "Hinweise Hinzufuegen", 
	"africa_stalking_username" => "Africa Stalking Username", 
	"planer" => "Planer",  
	"kalender" => "Kalender", 
	"standorten" => "Standorten", 
	"income_in" => "Einkommen in <strong>( __1__ )</strong>", 
	"termine" => "Termine", 
	"preview" => "Vorschau", 
	"payment_reminder" => "Zahlungserrinerung", 
	"Rechnungsnummer" => "Rechnungsnummer",
	"Fahrschüler" => "Fahrschüler",
	"read_note" => "Notizen lesen", 
	"delete_question" => "Frage Löschen", 
	"register" => "Registrieren", 
	"this_class_with_its_chapters_and_lectures_will_be_deleted" => "Diese Klasse und ihre zugehörigen Lektionen und Daten werden gelöscht.",
	"remember_me"=>"Erinnere dich an mich",
	"accept_terms"=>"Ich stimme den Bedingungen zu",
	"create_user_account"=>"Benutzerkonto anlegen",	
	"instructors_gender" => "Fahrlehrer/innen",

	"karteikennung" => "Karteikennung", 
	"fuehrerschein_class" => "Führerschein Klasse(n)", 
	"a" => "A", 
	"b" => "B", 
	"c" => "C", 
	"erteilungsart" => "Erteilungsart", 
	"ersterwerb" => "Ersterwerb", 
	"preisliste" => "Preisliste", 
	"anmeldedatum" => "Anmeldedatum", 
	"anrede" => "Anrede", 
	"mr" => "Herr", 
	"mrs" => "Frau", 
	"plz_ort" => "Plz, Ort", 
	"plz" => "Plz", 
	"ort" => "Ort", 
	"street_nr" => "Straße, Nr", 
	"staatsangehoerigkeit" => "Staatsangehörigkeit", 
	"ausweis_nr" => "Ausweis-Nr", 
	"language" => "Sprache", 
	"erweiterung" => "Erweiterung", 
	"englisch" => "Englisch", 
	"deutsch" => "Deutsch", 
	"franzoesisch" => "Französisch", 
	"griechisch" => "Griechisch", 
	"italienisch" => "Italienisch", 
	"polnisch" => "Polnisch", 
	"portugiesisch" => "Portugiesisch", 
	"rumaenisch" => "Rumänisch", 
	"russisch" => "Russisch", 
	"kroatisch" => "Kroatisch", 
	"spanisch" => "Spanisch", 
	"tuerkisch" => "Türkisch", 
	"arabisch_hocharabisch" => "Arabisch (Hocharabisch)", 
	"job" => "Beruf",	
	"bf17" => "bF17", 
	"license_class"=>"Klasse",
	"send_sms"=>"Nachricht Senden",
	"schedule_updated" => "Zeitplan aktualisiert",
	"schedule_set" => "Zeitplan festgelegt",
	"translate" => "de",
	"all" => "Alle",
	"Copy" => "Copie",
	"copy" => "copie",
	"Reset" => "Zurücksetzen"
];
?>