<?php 

/** 
* 
* THIS file should contain
* translation string for englisch
* 
*/
$sch_user_defined_en_languages_strings =[
	"branch_created" => "Branch Created", 
	"fuehrerscheinantrag" => "Driving License Application",
	"theorieunterricht" => "Theory Lessons",
	"praktischer_unterricht" => "Practical Lessons",
	"hinweise" => "Hints",
	"hinweise_zur_ausbildung" => "Information for Training",
	"hinweise_zur_prufueng" => "Hints for Exams",
	"tipps" => "Tips",
	"manage_notes" => "Manage Notes. To edit, click on a note or word. When you create a note with the heading 'Hinweise', the heading will be shown in red in the Mobile App.",
	"hint_hinzufuegen" => "Add note",
	"hinweise_bearbeiten_und_erstellen" => "Edit and create notes",
	"hinweisenname" => "Hint heading",
	"hinweisenueberschrift" => "Hint heading",
	"hinweisentext" => "Notice text",
	"cancel" => "Cancel",
	"hinweis_loeschen" => "Delete Hint",
	"hinweis_gespeichert" => "Hint Saved",
	"hinweis_wurde_erfolgreich_geloescht" => "Note was deleted successfully",
	"back" =>"Go Back",

	"all_child_notes_will_be_deleted"=> "Caution! If you delete a hint group, all hints in this group will also be deleted.",
	"fuehrerscheinantrag_description"=> "Here you can list the necessary documents as information for the learner drivers.",
	"add_new_line"=> "Add new line",
	"auflistungsart"=> "Listing type",
	"auflistungsart_desc"=> "How should the notes be displayed in the app",
	"checkbox"=> "With a Checkbox",
	"akkordion"=> "With an Accordion",
	"checkbox_desc"=> "This list will be displayed as a checkbox in the app.",
	"akkordion_desc"=> "This list will be displayed as an accordion in the app.",
	"to_group_adden"=> "Add to group",
	"to_group_adden_with_var"=> "Add note to __1__",
	"empty_here_in"=> "No entries available in '__1__'",
	"vorschau_ansehen"=> "View App in App",
	"hinweise_hinzufuegen"=> "Add Notes",

	"africa_stalking_username" => "Africa's talking Username", 
	"planer" => "Planer",  
	"kalender" => "Calendar",  
	"standorten" => "Locations", 
	"income_in" => "Income in <strong>( __1__ )</strong>", 
	"termine" => "Appointments", 
	"preview" => "Preview", 
	"Rechnungsnummer" => "Bill Number",
	"Fahrschüler" => "Learner",
	"payment_reminder" => "Payment reminder", 
	"read_note" => "Read Note", 
	"delete_question" => "Delete question", 
	"this_message_record_will_be_deleted" => "This message record will be deleted",
	"register" => "Register", 
	"this_class_with_its_chapters_and_lectures_will_be_deleted" => "This class with it's chapters and lectures will be deleted.",
	"remember_me"=>"Remember me",
	"accept_terms"=>"I accept the terms and conditions",
	"create_user_account"=>"Create Account",
	"instructors_gender" => "Instructors",
	"Klasse" => "Class",
	"Zahlstatus" => "Payment Status",
	"Standort" => "Location",
	"karteikennung" => "Kartei recognition", 
	"fuehrerschein_class" => "License type", 
	"a" => "A", 
	"b" => "B", 
	"c" => "C", 
	"erteilungsart" => "Acquisition Type", 
	"ersterwerb" => "First Timer", 
	"preisliste" => "Price list", 
	"anmeldedatum" => "Registration date", 
	"anrede" => "Title", 
	"mr" => "Mr", 
	"mrs" => "Mrs", 
	"plz_ort" => "Plz, City", 
	"plz" => "Plz", 
	"ort" => "City", 
	"street_nr" => "Street, Nr", 
	"staatsangehoerigkeit" => "Nationality", 
	"ausweis_nr" => "Card Nr", 
	"language" => "Language", 
	"erweiterung" => "Erweiterung", 
	"englisch" => "English", 
	"deutsch" => "German", 
	"franzoesisch" => "French", 
	"griechisch" => "Greek", 
	"italienisch" => "Italian", 
	"polnisch" => "Polish", 
	"portugiesisch" => "Portugese", 
	"rumaenisch" => "Rumanish", 
	"russisch" => "Russian", 
	"kroatisch" => "Croatian", 
	"spanisch" => "Spanish", 
	"tuerkisch" => "Turkish", 
	"arabisch_hocharabisch" => "Arabic (Standard arabic)", 
	"job" => "Job", 	
	"bf17" => "bF17",
	"license_class"=> "Type",
	"schedule_updated" => "Schedule updated",
	"translate" => "en",
	"all" => "all",
	"_amt_active_students"=>"__1__ Active Students",
	"_amt_inactive_students"=>"__1__ Inactive Students"

];


?>